### ISSUE TITLE
Research Android Application Needs

### ISSUE THREAD

**Issue by DerekCresswell** [CSC207-UofT/course-project-gries-fan-club#28]
Research into the requirements for building an Android application. We need to know a few things:
- The overall class structure for creating an Android app and how our current code will need to shift and adapt.
- Relevant tools and libraries we will need to efficiently work with the platform
- What type of features can we expect to implement here? Is the tinder swipe crazy complicated? How about simple menus? Just a general idea of what we will be able to code within our short time frame.

Feel free to try a first crack at implementing it to the project if it helps. Report here with your findings.

**Comment by ayushsahi** [comment]
**The android aspect of the project can be classified into three parts:
1. UI Construction
2. Backend Integration
3. Testing**

**1. UI Construction**
Using the Android API provided by Google, Android apps are able to compile and run Java code as class files, these class files are further compiled as DEX files as there is no JVM in Android. The DEX files are then bundled into what is called an APK, which is an installable package for Android devices). For more information on how code is compiled an executed read the following web pages: 
- [Link 1](https://subscription.packtpub.com/book/application_development/9781785883262/1/ch01lvl1sec09/how-java-and-android-work-together)
- [Link 2](https://javarevisited.blogspot.com/2013/06/introduction-of-how-android-works-Java-programmers.html#axzz7B12WAiHA)

Implementing UI elements in Android is a very straight forward procedure based on my research. There are many pre-exisiting classes that allow us to create objects like [buttons](https://developer.android.com/reference/android/widget/Button) and [menus](https://developer.android.com/guide/topics/ui/menus) in the Android API. These packages range from everything to Android gestures  and app animations. For a full comprehensive list on packages, click [here](https://developer.android.com/reference/packages). 

The UI can be built using the design principles shown in the [Model View Presenter article](https://medium.com/cr8resume/make-you-hand-dirty-with-mvp-model-view-presenter-eab5b5c16e42) provided on Piazza. The principles in this article are intuitive and logical so implementation should not be very complicated especially since we can consult with out TA during Phase 2. 

Building the front end skeleton (which I define as writing the code for creating and organizing all the necessary objects with the desired graphics without connecting them to any back end functions, meaning when a button is clicked nothing actually occurs) is a task that looks to take close to **10-15 hours, or 2 days worth of coding**, however it could take more as this would be new to all of us. I believe the plan should be to **finish this by November 5th**. 

**2. Backend Integration**
Not much to say here other than this will be the hardest part of the Android implementation. Connecting any object in the UI (like a button) with a backend function should be straightforward to code, the concern lies in maintaining the CRC structure and maintaining our recipe data set according to Clean Architecture and MVP may be a challenge. 

**3. Testing**
Testing in Android is very robust. There are many virtual machines we can use to test the app. The code we write can be compiled into an APK and ran on our phones as well. I personally believe we should test our code iteratively however we can find other amenable systems. Writing unit tests for Android code is possible will go a long way in ensuring our code works. The different types of unit testing in Android are available [here](https://developer.android.com/training/testing/fundamentals).

**Comment by DerekCresswell** [comment]
In this front end skeleton, can we create a menu emulating the options described in the specification from phase 0?

Then each execution of a button can lead to a (for now empty) entry state into the  "backend" of the program. For instance, search for tags should leave us into an entry point with a list of tag names so we can call into a use case of our program? Might be good idea to do the UI over many pr's and into a quasi-main branch for the time being?

Also, we would want to run code like loading recipes once when the app starts then each button press entry point can access the already loaded storages etc.?

**Comment by pritheeroy** [comment]
****In this front-end skeleton, can we create a menu emulating the options described in the specification from phase 0?
Most definitely. Are you thinking of just doing a simple screen with a few buttons you can press to get to what you want?
